/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.jfrog.autotest.api.tests;

import org.testng.annotations.Test;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.containsString;
import static org.hamcrest.Matchers.hasKey;

import java.io.File;
import java.io.IOException;
import java.time.Instant;

public class ArtifactsTest {

	long now = Instant.now().toEpochMilli();
	String fileName = "apiTest" + now + ".txt";

	@Test(priority = 1)
	public void DeployArtifact() {
		File temp = null;
		try {
			temp = File.createTempFile(fileName, ".txt");
		} catch (IOException e) {
			e.printStackTrace();
		}
		temp.deleteOnExit();

		given()
			.multiPart("file", temp)
		.when()
			.put("/artifactory/generic-local/my/apitest/artifact/directory/" + fileName)
		.then()
			.statusCode(201)
			.body("downloadUri",containsString("/artifactory/generic-local/my/apitest/artifact/directory/" + fileName));
	}
	
	@Test(priority = 2)
	public void GetFileStats() {
		given()
			.queryParam("stats", "")
		.when()
			.get("/artifactory/api/storage/generic-local/my/apitest/artifact/directory/" + fileName)
		.then()
			.statusCode(200)
			.body("", hasKey("downloadCount"));
	}

	@Test(priority = 3)
	public void DeleteArtifact() {
		given()
		.when()
			.delete("/artifactory/generic-local/my/apitest/artifact/directory/" + fileName)
		.then()
			.statusCode(204);
	}

}
